import {
  pgTable,
  varchar,
  text,
  integer,
  bigint,
  bigserial,
  real,
  doublePrecision,
  boolean,
  timestamp,
  primaryKey,
  uuid,
  unique,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// ===========================
// Users Table
// ===========================
export const users = pgTable('Users', {
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  lbusername: varchar('lbusername').primaryKey(),
  following: integer('following'),
  followers: integer('followers'),
  numberOfLists: integer('number_of_lists'),
  isDiscord: boolean('is_discord'),
  displayName: text('display_name'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const usersRelations = relations(users, ({ many }) => ({
  ratings: many(userRatings),
  films: many(userFilms),
}));

// ===========================
// UserRatings Table
// ===========================
export const userRatings = pgTable(
  'UserRatings',
  {
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    username: varchar('username').notNull(),
    rating: real('rating').notNull(),
    count: integer('count'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  },
  (table) => [primaryKey({ columns: [table.username, table.rating] })]
);

export const userRatingsRelations = relations(userRatings, ({ one }) => ({
  user: one(users, {
    fields: [userRatings.username],
    references: [users.lbusername],
  }),
}));

// ===========================
// UserFilms Table
// ===========================
export const userFilms = pgTable(
  'UserFilms',
  {
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    filmSlug: varchar('film_slug').notNull(),
    rating: real('rating'),
    lbusername: varchar('lbusername').notNull(),
    watched: timestamp('watched', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    liked: boolean('liked'),
    title: varchar('title'),
  },
  (table) => [primaryKey({ columns: [table.lbusername, table.filmSlug] })]
);

export const userFilmsRelations = relations(userFilms, ({ one }) => ({
  user: one(users, {
    fields: [userFilms.lbusername],
    references: [users.lbusername],
  }),
}));

// ===========================
// FilmRatings Table
// ===========================
export const filmRatings = pgTable(
  'FilmRatings',
  {
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at').defaultNow(), // no timezone per schema
    filmSlug: text('film_slug').notNull(),
    rating: real('rating').notNull(),
    ratingCount: integer('rating_count'),
  },
  (table) => [primaryKey({ columns: [table.filmSlug, table.rating] })]
);

// ===========================
// Films Table
// ===========================
export const films = pgTable('Films', {
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  filmSlug: varchar('film_slug').primaryKey(),
  lbRating: real('lb_rating'),
  url: varchar('url'),
  tmdbLink: varchar('tmdb_link'),
  poster: varchar('poster'),
  banner: varchar('banner'),
  title: varchar('title'),
});

// ===========================
// MFLUserMovies Table
// ===========================
export const mflUserMovies = pgTable(
  'MFLUserMovies',
  {
    username: varchar('username').notNull(),
    title: varchar('title').notNull(),
    filmSlug: text('film_slug'),
  },
  (table) => [primaryKey({ columns: [table.username, table.title] })]
);

// ===========================
// MFLScoringMetrics Table
// ===========================
export const mflScoringMetrics = pgTable('MFLScoringMetrics', {
  metricId: bigint('metric_id', { mode: 'number' }).primaryKey(),
  metric: text('metric'),
  metricName: text('metric_name'),
  category: text('category'),
  scoringCondition: text('scoring_condition'),
  pointValue: bigint('point_value', { mode: 'number' }),
});

// ===========================
// MFLScoringTally Table
// ===========================
export const mflScoringTally = pgTable('MFLScoringTally', {
  filmSlug: text('film_slug'),
  metricId: bigint('metric_id', { mode: 'number' }),
  pointsAwarded: bigint('points_awarded', { mode: 'number' }),
  // scoring_id is auto-generated by database sequence
  scoringId: bigserial('scoring_id', { mode: 'number' }).primaryKey(),
});

export const mflScoringTallyRelations = relations(mflScoringTally, ({ one }) => ({
  metric: one(mflScoringMetrics, {
    fields: [mflScoringTally.metricId],
    references: [mflScoringMetrics.metricId],
  }),
}));

// ===========================
// MFLMovieData Table
// ===========================
export const mflMovieData = pgTable('MFLMovieData', {
  title: text('title'),
  price: real('price'),
  rosters: bigint('rosters', { mode: 'number' }),
  boxOfficePoints: text('box_office_points'),
  awardsPoints: bigint('awards_points', { mode: 'number' }),
  criticalPerfPoints: text('critical_perf_points'),
  totalPoints: bigint('total_points', { mode: 'number' }),
  pointsPerDollar: doublePrecision('points_per_dollar'),
  filmSlug: text('film_slug'),
});

// ===========================
// AwardShows Table
// ===========================
export const awardShows = pgTable('AwardShows', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: varchar('name').notNull().unique(),
  slug: varchar('slug').notNull().unique(),
  description: varchar('description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const awardShowsRelations = relations(awardShows, ({ many }) => ({
  events: many(events),
}));

// ===========================
// Events Table
// ===========================
export const events = pgTable('Events', {
  id: uuid('id').defaultRandom().primaryKey(),
  awardShowId: uuid('award_show_id').notNull().references(() => awardShows.id),
  name: varchar('name').notNull(),
  slug: varchar('slug').notNull().unique(),
  year: integer('year').notNull(),
  editionNumber: integer('edition_number'),
  nominationsDate: timestamp('nominations_date', { withTimezone: true }),
  awardsDate: timestamp('awards_date', { withTimezone: true }),
  status: varchar('status', { length: 20 }).notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const eventsRelations = relations(events, ({ one, many }) => ({
  awardShow: one(awardShows, {
    fields: [events.awardShowId],
    references: [awardShows.id],
  }),
  categories: many(eventCategories),
}));

// ===========================
// EventCategories Table
// ===========================
export const eventCategories = pgTable('EventCategories', {
  id: uuid('id').defaultRandom().primaryKey(),
  eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }),
  name: varchar('name').notNull(),
  displayOrder: integer('display_order').notNull(),
  displayMode: varchar('display_mode', { length: 20 }).notNull().default('movie_first'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const eventCategoriesRelations = relations(eventCategories, ({ one, many }) => ({
  event: one(events, {
    fields: [eventCategories.eventId],
    references: [events.id],
  }),
  nominees: many(eventNominees),
  picks: many(eventUserPicks),
}));

// ===========================
// EventNominees Table
// ===========================
export const eventNominees = pgTable('EventNominees', {
  id: uuid('id').defaultRandom().primaryKey(),
  categoryId: uuid('category_id').notNull().references(() => eventCategories.id, { onDelete: 'cascade' }),
  personName: varchar('person_name'),
  movieOrShowName: varchar('movie_or_show_name').notNull(),
  isWinner: boolean('is_winner').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const eventNomineesRelations = relations(eventNominees, ({ one, many }) => ({
  category: one(eventCategories, {
    fields: [eventNominees.categoryId],
    references: [eventCategories.id],
  }),
  picks: many(eventUserPicks),
}));

// ===========================
// EventUserPicks Table
// ===========================
export const eventUserPicks = pgTable(
  'EventUserPicks',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    categoryId: uuid('category_id').notNull().references(() => eventCategories.id, { onDelete: 'cascade' }),
    userId: varchar('user_id').notNull(),
    nomineeId: uuid('nominee_id').notNull().references(() => eventNominees.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  },
  (table) => [unique().on(table.categoryId, table.userId)]
);

export const eventUserPicksRelations = relations(eventUserPicks, ({ one }) => ({
  category: one(eventCategories, {
    fields: [eventUserPicks.categoryId],
    references: [eventCategories.id],
  }),
  nominee: one(eventNominees, {
    fields: [eventUserPicks.nomineeId],
    references: [eventNominees.id],
  }),
}));

// ===========================
// Type Exports
// ===========================
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type UserRating = typeof userRatings.$inferSelect;
export type NewUserRating = typeof userRatings.$inferInsert;

export type UserFilm = typeof userFilms.$inferSelect;
export type NewUserFilm = typeof userFilms.$inferInsert;

export type FilmRating = typeof filmRatings.$inferSelect;
export type NewFilmRating = typeof filmRatings.$inferInsert;

export type Film = typeof films.$inferSelect;
export type NewFilm = typeof films.$inferInsert;

export type MFLUserMovie = typeof mflUserMovies.$inferSelect;
export type NewMFLUserMovie = typeof mflUserMovies.$inferInsert;

export type MFLScoringMetric = typeof mflScoringMetrics.$inferSelect;
export type NewMFLScoringMetric = typeof mflScoringMetrics.$inferInsert;

export type MFLScoringTallyRow = typeof mflScoringTally.$inferSelect;
export type NewMFLScoringTally = typeof mflScoringTally.$inferInsert;

export type MFLMovieDataRow = typeof mflMovieData.$inferSelect;
export type NewMFLMovieData = typeof mflMovieData.$inferInsert;

export type AwardShow = typeof awardShows.$inferSelect;
export type NewAwardShow = typeof awardShows.$inferInsert;

export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;

export type EventCategory = typeof eventCategories.$inferSelect;
export type NewEventCategory = typeof eventCategories.$inferInsert;

export type EventNominee = typeof eventNominees.$inferSelect;
export type NewEventNominee = typeof eventNominees.$inferInsert;

export type EventUserPick = typeof eventUserPicks.$inferSelect;
export type NewEventUserPick = typeof eventUserPicks.$inferInsert;
